import React, { useState } from 'react';
import { ImageIcon, DownloadIcon } from 'lucide-react';
export function GeneratorForm() {
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedImage, setGeneratedImage] = useState('');
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;
    setIsGenerating(true);
    // Simulate image generation
    setTimeout(() => {
      // Using a placeholder image
      setGeneratedImage('https://images.unsplash.com/photo-1579546929518-9e396f3cc809?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80');
      setIsGenerating(false);
    }, 2000);
  };
  return <div className="w-full max-w-3xl mx-auto">
      <form onSubmit={handleSubmit} className="mb-8">
        <div className="mb-4">
          <label htmlFor="prompt" className="block text-gray-700 font-medium mb-2">
            Describe the image you want to generate
          </label>
          <textarea id="prompt" value={prompt} onChange={e => setPrompt(e.target.value)} className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" rows={4} placeholder="E.g., A serene landscape with mountains and a lake at sunset" required />
        </div>
        <button type="submit" disabled={isGenerating} className={`px-6 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors flex items-center justify-center ${isGenerating ? 'opacity-70 cursor-not-allowed' : ''}`}>
          {isGenerating ? <>
              <svg className="animate-spin -ml-1 mr-2 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              Generating...
            </> : <>
              <ImageIcon className="mr-2 h-5 w-5" />
              Generate Image
            </>}
        </button>
      </form>
      {generatedImage && <div className="bg-white p-4 rounded-lg shadow-md">
          <h3 className="font-medium text-lg mb-4">Generated Image</h3>
          <div className="relative">
            <img src={generatedImage} alt="AI generated image" className="w-full h-auto rounded-md" />
            <div className="absolute bottom-3 right-3 bg-white bg-opacity-70 px-2 py-1 rounded text-xs">
              Generated by MarkAI
            </div>
          </div>
          <div className="mt-4 flex justify-end">
            <button className="flex items-center px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors">
              <DownloadIcon className="mr-2 h-4 w-4" />
              Download Image
            </button>
          </div>
        </div>}
    </div>;
}